- docs/guia_definicion_assets.md
- docs/guias/_category_.json
- docs/guias/guia_definicion_assets.md
- docusaurus.config.js
- package.json
- yarn.lock
La guía se vería [algo así](https://github.com/Taro-IT/docs/blob/15_guia_para_definicion_de_assets/docs/guias/guia_definicion_assets.md) en la wiki. 
Toda la parte de árbol de decisiones se va a ver así 
Closes #15
> 15 guia para definicion de assets

- docs/plantillas/PL6-plantilla-para-procesos.md
- docs/procesos/P02-proceso-juntas-socios-formadores.md
[Aquí](https://github.com/Taro-IT/docs/blob/27_plantilla_de_procesos/docs/plantillas/PL6-plantilla-para-procesos.md) está la liga para que vean la plantilla. También cambie el valor de puntualidad por el de responsabilidad y agregué a los que faltaban en la parte de auditoría en el proceso P02. Eso lo pueden checar [aquí](https://github.com/Taro-IT/docs/blob/27_plantilla_de_procesos/docs/procesos/P02-proceso-juntas-socios-formadores.md)
Closes #27
> 27 plantilla de procesos

- docs/codigo-etica.md
> docs(ethics-code): create initial version

- docs/guias/G05-guia-platicas-1-a-1.md
Guide and bullet questions to manage the conversations
> feat: Guide for 1 to 1 talks

- docs/procesos/P05-proceso-requisitos.md
feat: We start the process to obtain requirements begins
> P05 - proceso de requisitos 

- docs/procesos/P07-proceso-juntas-diarias.md
Se agrega el proceso de juntas diarias.
Closes #40
> feat(documentation): agregar proceso para juntas diarias P07

- docs/procesos/P12-proceso-definicion-objetivos.md
Se agrega el proceso para la definición de objetivos
Fix #51
> feat: agregar proceso para definición de objetivos

- docs/procesos/P13-proceso-generar-alimentar-historias-usuario.md
> docs(process): create user story process

- docs/politicas/POL04-Definicion de elementos de configuracion.md
…, abarcando procesos, politicas y lineas de codigo
> POL04-Definicion de elementos de la configuracion

- docs/procesos/P15-proceso-planeacion-de-iteracion.md
> P15 - Typofix

- docs/procesos/P09-proceso-entrega-de-scampi.md
Se añadió un paso para verificar que los documentos ligados al tablero SCAMPI tengan permisos para ver.
> fix(P02): add step for permission verification

- docs/codigo-etica.md
Se creó un apartado para los autores en el código de ética
> fix(docs): update ethics code

- docs/guias/G07-guia-wbs.md
- docs/plantillas/PL13-plantilla-wbs.md
- add WBS template
- add definition of WBS
- add definition of WBS levels
> refactor(G07): add definition of WBS levels

- docs/checklists/CH13-cambios-en-requisitos.md
> feat: add requirements changes doc checklist

- docs/guias/G22-guia-para-estimar-workitem.md
Se añadió una guía para estimar un work item, ya sea con datos históricos o no.
> docs: se agrego G22 - Guia para estimar un work item

- docs/procesos/P15-proceso-planeacion-de-iteracion.md
Se añadieron los pasos para revisar el WBS y el plan de recursos
Se añadió PP 1.4 a la fase 2
> docs: hacer referencia al plan de recursos y el WBS en el P15

- docs/guias/G08-guia-para-el-pm.md
- docs/guias/G09-guia-team-leader.md
- docs/guias/G10-guia-del-PO.md
- docs/guias/G14-guia-architecture-owner.md
- docs/guias/G17-guia-defect-log.md
- docs/guias/G18-guia-reversion-codigo.md
- docs/guias/G22-guia-para-estimar-workitem.md
refactor G14, G17, G18, G22, G10, G09 y G08
> refactor-de-guias

- docs/checklists/CH08-entrega-de-SCAMPI.md
- docs/codigo-etica.md
- docs/politicas/POL03-politica-manejo-datos.md
- docs/procesos/P09-proceso-entrega-de-scampi.md
Se agregaron las medidas de prevención y la de acción para la protección de los datos.
> docs: medidas de prevencion a POL03

- docs/guias/G26-guia-para-evaluaciones-individuales.md
Se agregó una guía para las competencias.
> docs: guia para competencias

- docs/intro.md
Añadir el pie de pagina con agradecimientos y derecho de uso
> docs: agradecimientos
